### ISSUE TITLE
BadBoy_Levels

### ISSUE THREAD

**Issue by ForeverTheGM** [TekNoLogic/friendswithbenefits#1]
Using this addon with funkydude's BadBoy_Levels addon causes me to receive this error whenever someone that isn't already on my friends list whispers me.

"Friends With Benefits: 'Friend added' message when removing a friend. Disabling for the rest of this session."

http://forums.wowace.com/showthread.php?p=286600#post286600

**Comment by tekkub** [comment]
I've pushed a fix, it will be released soon.  This fix will only work with the update to BBL that funky's working on right now.

**Comment by ForeverTheGM** [comment]
Thank you!
