### ISSUE TITLE
FWB re-adds removed friends

### ISSUE THREAD

**Issue by MakotoFatora** [TekNoLogic/friendswithbenefits#2]
After removing a friend from one character's list, I log out and log back in, and the friend is re-added, presumably since the friend still exists on my other alts on the server.

Is this expected behavior or is there a way to get FWB to remove it from the list so it won't be re-added?  I can probably go find the lists in the data files somewhere but that seems cumbersome.  If this is Works-as-designed though I'll deal with it :)

FWB Version:

**Comment by tekkub** [comment]
FWB should detect removal... so long as it was loaded and active when you did it.
