### ISSUE TITLE
Not Working As Of 5.1

### ISSUE THREAD

**Issue by raysmith59** [TekNoLogic/friendswithbenefits#6]
Just seems to have stopped working as of 5.1... I'm not seeing anything in chat when I log in and when I remove a friend from one toon it isn't replicated across other toons.

EDIT: Actually, it now seems that the removed friend is put back in when I go back to that toon.  So, possible that it's okay adding friends but not removing them.

**Comment by tekkub** [comment]
Fixed in cb78543aeff9a7de1a5a3ed5d96160580cf0536f
